# Etapa base
FROM node:18-alpine AS base

WORKDIR /app

COPY package*.json ./

# Etapa de construcción
FROM base AS builder

COPY . .
RUN npm ci
RUN npx prisma generate
RUN npx nx run-many -t build --all --prod

# Etapa de producción
FROM node:18-alpine AS production
WORKDIR /app
COPY package*.json .
COPY ecosystem.config.js .
RUN npm ci --omit=dev
COPY --from=builder /app/node_modules/.prisma ./node_modules/.prisma
COPY --from=builder /app/dist ./dist
RUN npm install pm2 -g
EXPOSE 3333
CMD ["pm2-runtime", "ecosystem.config.js"]
